spring.application.name=dofocus

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/do_focus
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


#jwt configurations
spring.app.jwtSecret=jwtdjjhhsuudnhehrhjjkwhbhhfhshhjdhhfjshfhihiahkhuueiiksbu
spring.app.jwtExpirationMs=12000000


spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
