spring.application.name=onetoone

# ===============================
# =  Database Configuration     =
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/springbootonetoone
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# =  Hibernate Configuration    =
# ===============================

# Automatically create/update table based on Entities
spring.jpa.hibernate.ddl-auto=create

# Show SQL in console
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

# Set Hibernate dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

