logging.file.name=app.log
spring.application.name=journalApp
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journal_db
#spring.data.mongodb.username=abc
#spring.data.mongodb.password=1234