spring.application.name=myauthapp

#one of the main user of my application
#abhee mai yml se krta hun taki practice ho jaye


#jsp configuration
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

#spring:
#mvc:
#view:
#prefix: /views
#suffix: .jsp
